### ISSUE TITLE
Question about Eq. 10

### ISSUE THREAD

**Issue by LoveMiki** [00why00/Glocal#10]
Hi,
I'm quite confused about the objective of Eq. 10. What does $E^{x_i}$ stand for in the equation? I assume that it stands for negative log-likelihood in Eq.15. As stated in the paper, $M_k$ is set to -1 and $M_u$ is set to 1, then $L_e^{x_i}$ becomes $E^{x_i}+1$ when $y_i$ is the known label while becoming $E^{x_i}-1$ when $y_i$ is the unknown label. To minimize the loss of GEL, all values of $L_e^{x_i}$ are supposed to be near 0, so $E^{x_i}$ should be smaller than or near -1 when $y_i$ is known label and $E^{x_i}$ should be smaller than 1. If this is right, how can $E^{x_i}$ be negative values?
Please correct me if I am wrong.
Best regard.

**Comment by LoveMiki** [comment]
I have checked the code and found out that $E^{x_i}$ represents the distance or similarity value rather than the probability distribution. And I noticed that you used learnable $M_k$ and $M_u$ instead of the fixed values. But it seems that the paper did not mention it.

**Comment by 00why00** [comment]
I'm sorry for not getting back to you sooner.
We experimented with the margin setting of energy loss in the ablation experiment subsection. As shown in Table 3 in our paper, using fixed values can achieve better AUROC.

**Comment by 00why00** [comment]
I'm sorry for not getting back to you sooner.
The learnable margin is what we used in previous experiments, but from our experimental results, the learnable margin does not improve the performance of the task, so we still maintain a fixed margin for experiments, as we did not add --learnable_margin option in running examples in README.
