### ISSUE TITLE
Why did you use the meta-trained model of FEAT to meta-train GEL?

### ISSUE THREAD

**Issue by LoveMiki** [00why00/Glocal#14]
Hi,
the pre-trained models you provided include the weights of multi-head self-attention, how did you pre-train the model?
And I used the meta-trained models of FEAT to train GEL, which are the same size as the pre-trained models you provided and show a similar training trajectory.
Could you provide the code of pre-training?
Thanks.

**Comment by 00why00** [comment]
Sorry for the late response.

We use the meta-trained models of FEAT to train GEL.
Consistent with what is described in the paper, in the pre-training phase, we added rotation as same as TANE to ensure the fairness of the comparison. And the pertaining code is [here](https://github.com/00why00/Glocal/files/14280122/pretrain.zip). You can use it to replace the corresponding file in [FEAT](https://github.com/Sha-Lab/FEAT) for pre-training.

https://github.com/shiyuanh/TANE/blob/fe089d477ba9387dd2d008d8872cdc84f8ad77ed/pretrain/trainer/PreTrainer.py#L14-L21

**Comment by LoveMiki** [comment]
> Sorry for the late response.
> 
> We use the meta-trained models of FEAT to train GEL. Consistent with what is described in the paper, in the pre-training phase, we added rotation as same as TANE to ensure the fairness of the comparison. And the pertaining code is [here](https://github.com/00why00/Glocal/files/14280122/pretrain.zip). You can use it to replace the corresponding file in [FEAT](https://github.com/Sha-Lab/FEAT) for pre-training.
> 
> https://github.com/shiyuanh/TANE/blob/fe089d477ba9387dd2d008d8872cdc84f8ad77ed/pretrain/trainer/PreTrainer.py#L14-L21

Yes, I understand it is consistent with the description in the paper. However, it is not so common for one FSL or FSOR to use the meta-trained model from the other method as this could bring unfair comparisons to other methods and lead to the conclusion that the so-called performance increased. As mentioned in issue #13, the performance of GEL dramatically dropped without using the meta-trained model of FEAT, which seems that GEL's performance mainly relies on the FEAT's model rather than the proposed method.
