### ISSUE TITLE
About Dataset Format

### ISSUE THREAD

**Issue by hoho303** [00why00/Glocal#2]
Thank you for your good work !

I followed your instructions to reproduce the results. However, I encountered an issue with the dataset format downloaded from the link in your repository. Your code requires CSV files and an image folder, but the files I obtained after extracting the downloaded package are in pickle format. 

What steps can I take to convert the pickle files to the required format for your code?

**Comment by 00why00** [comment]
Thanks for your issue!

MiniImagetNet needs CSV files to split datasets, We follow [SnaTCHer](https://github.com/Sha-Lab/FEAT) and use the same split of Ravi & Larochelle. You can download the split file [here](https://github.com/twitter-research/meta-learning-lstm/tree/master/data/miniImagenet) and use `pickle` to preprocess pickle files into images or just download the original images [here](https://www.kaggle.com/datasets/arjunashok33/miniimagenet).

**Comment by hoho303** [comment]
"Thank you for your response.

I have resolved that issue. Additionally, I have another question.

How many GPUs did you use to train the model?"

**Comment by 00why00** [comment]
Sorry for the late response.

We use a single NVIDIA 3090 to train our model.

**Comment by hoho303** [comment]
The issue has been resolved, so I will close it here.

Thank you very much!
