### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by David-655** [00why00/Glocal#3]
Can you share dataset:"tiered-imagenet" again?

**Comment by David-655** [comment]
In the code, the way to load images and labels just like :
"file_path = {
            'train': [os.path.join(npz_path, 'train_images.npz'), os.path.join(npz_path, 'train_labels.pkl')],
            'val': [os.path.join(npz_path, 'val_images.npz'), os.path.join(npz_path, 'val_labels.pkl')],
            'test': [os.path.join(npz_path, 'test_images.npz'), os.path.join(npz_path, 'test_labels.pkl')]}

        image_path = file_path[set_name][0]
        label_path = file_path[set_name][1]

        data_train = load_data(label_path)
        labels = data_train['labels']
        self.data = np.load(image_path)['images']"

But this is not the same format as the dataset I found earlier.
The dataset is now structured as follows:
class_names.txt
synsets.txt
test_images_png.pkl
test_labels.pkl
train_images_png.pkl
train_labels.pkl
val_images_png.pkl
val_labels.pkl

**Comment by 00why00** [comment]
Sorry for the late response.

We follow [SnaTCHer](https://github.com/Sha-Lab/FEAT) and use the same code to load tiered-imagenet. We used the Google Drive shareable link given by the author of the dataset, but it seems to be expired, we have submitted an [issue](https://github.com/renmengye/few-shot-ssl-public/issues/22) in their repository, you can keep an eye on it or temporarily use some alternative [link](https://github.com/kjunelee/MetaOptNet) to download it.

**Comment by David-655** [comment]
Thanks for your response.
