### ISSUE TITLE
Questions about the split between suppor and query?

### ISSUE THREAD

**Issue by jianandeng023** [00why00/Glocal#4]
in the https://github.com/00why00/Glocal/blob/master/model/models/base.py line 50.
Why support also needs to include unseen images in the open set, few-shot open-set recognition should not be that support consists of seen classes, while query consists of seenand unseen classes.
Thank you very much for your answer
I wish you all the best

**Comment by 00why00** [comment]
Thank you for your attention.

The reason why we do this is that it is convenient to write the few-shot open-set data loader for data reading. Although the open-set samples are added to the support set, we will remove them [here](https://github.com/00why00/Glocal/blob/master/model/models/base.py#L90) and only keep the closed-set samples.

**Comment by jianandeng023** [comment]
> Thank you for your attention.
> 
> The reason why we do this is that it is convenient to write the few-shot open-set data loader for data reading. Although the open-set samples are added to the support set, we will remove them [here](https://github.com/00why00/Glocal/blob/master/model/models/base.py#L90) and only keep the closed-set samples.

ok thank you reply, I will close this issue.
