### ISSUE TITLE
The search for the dataset in your paper

### ISSUE THREAD

**Issue by codeWang-maker** [00why00/Glocal#6]
Dear Authors,

Your work titled "Glocal Energy-based Learning for Few-Shot Open-Set Recognition." has been very helpful to me.I want to replicate the effect of your model on the tieredimagenet dataset, But the download link you provided for this dataset has expired. Could you please provide it?

Thank you for your contribution to this field , and I look forward to your reply.

**Comment by 00why00** [comment]
Thank you for your attention! This issue #3  may help you.
