### ISSUE TITLE
Question about the pretrained weight

### ISSUE THREAD

**Issue by mushan05** [00why00/Glocal#7]
Dear Authors,

I hope this message finds you well.

I wanted to extend my gratitude for the excellent implementation of the work titled "Glocal Energy-based Learning for Few-Shot Open-Set Recognition." I would like to know how to train the pretrained weights and which class of data was used to train them. Your insights would be greatly appreciated.

Thank you once again for your valuable contribution to the field, and I look forward to hearing from you.

**Comment by 00why00** [comment]
Sorry for the late response.

We follow [TANE](https://github.com/shiyuanh/TANE) use the training set of each dataset to pretrain the backbone in a batch training way. For a fair comparison, we use the same image augmentation as [TANE](https://github.com/shiyuanh/TANE/blob/main/pretrain/trainer/PreTrainer.py).
